# Generated by Django 3.0.5 on 2020-07-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='vern',
            new_name='verb',
        ),
    ]
